name: Build TensorNote for Desktop

on:
  push:
    branches:
      - release

jobs:
  publish-tauri:
      permissions:
        contents: write
      strategy:
        fail-fast: false
        matrix:
          platform: [macos-latest, ubuntu-20.04, windows-latest]

      runs-on: ${{ matrix.platform }}
      steps:
        - uses: actions/checkout@v4

        - name: setup node
          uses: actions/setup-node@v4
          with:
            node-version: latest

        - name: install Rust stable
          uses: dtolnay/rust-toolchain@stable

        - name: install dependencies (ubuntu only)
          if: matrix.platform == 'ubuntu-20.04'
          run: |
            sudo apt-get update
            sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf

        - name: Setup wasm-pack
          uses: jetli/wasm-pack-action@v0.4.0
          with:
            version: latest

        - name: Add wasm32-unknown-unknown build target
          run: rustup target add wasm32-unknown-unknown

        - name: Setup pnpm
          uses: pnpm/action-setup@v3
          with:
            version: latest

        - name: install frontend dependencies
          run: pnpm install

        - uses: tauri-apps/tauri-action@v0
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            tagName: app-v__VERSION__ # the action automatically replaces \_\_VERSION\_\_ with the app version
            releaseName: 'App v__VERSION__'
            releaseBody: 'See the assets to download this version and install.'
            releaseDraft: true
            prerelease: false